spring:
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ENC(GZwhukEU94lr/i7mSsH3yO8VZ0ADMHpMc8b4NPsMIvmhYxa+mrdvaVndESGoe3gb)

logging:
  level:
    feign: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.feign: DEBUG

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator